# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commentShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_commentShow(object):
    def setupUi(self, commentShow):
        commentShow.setObjectName("commentShow")
        commentShow.resize(899, 582)
        self.verticalLayout = QtWidgets.QVBoxLayout(commentShow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(commentShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.commentShowWidget = QtWidgets.QWidget()
        self.commentShowWidget.setGeometry(QtCore.QRect(0, 0, 875, 558))
        self.commentShowWidget.setObjectName("commentShowWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.commentShowWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.commentShowMusicLabel = QtWidgets.QLabel(self.commentShowWidget)
        self.commentShowMusicLabel.setMinimumSize(QtCore.QSize(400, 0))
        self.commentShowMusicLabel.setMaximumSize(QtCore.QSize(400, 1000))
        self.commentShowMusicLabel.setStyleSheet("font: 18pt \"微软雅黑\";")
        self.commentShowMusicLabel.setObjectName("commentShowMusicLabel")
        self.horizontalLayout.addWidget(self.commentShowMusicLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CommentInputLabel = QtWidgets.QPlainTextEdit(self.commentShowWidget)
        self.CommentInputLabel.setObjectName("CommentInputLabel")
        self.verticalLayout_3.addWidget(self.CommentInputLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.CommentCommitButton = QtWidgets.QPushButton(self.commentShowWidget)
        self.CommentCommitButton.setFlat(True)
        self.CommentCommitButton.setObjectName("CommentCommitButton")
        self.horizontalLayout_2.addWidget(self.CommentCommitButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.commentShowWidget)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(commentShow)
        QtCore.QMetaObject.connectSlotsByName(commentShow)

    def retranslateUi(self, commentShow):
        _translate = QtCore.QCoreApplication.translate
        commentShow.setWindowTitle(_translate("commentShow", "Form"))
        self.commentShowMusicLabel.setText(_translate("commentShow", "音乐名称"))
        self.CommentCommitButton.setText(_translate("commentShow", "评论"))
