# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commentWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommentWidget(object):
    def setupUi(self, CommentWidget):
        CommentWidget.setObjectName("CommentWidget")
        CommentWidget.resize(856, 307)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CommentWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(CommentWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.commentUserLabel = QtWidgets.QLabel(CommentWidget)
        self.commentUserLabel.setStyleSheet("font: 14pt \"微软雅黑\";")
        self.commentUserLabel.setObjectName("commentUserLabel")
        self.verticalLayout.addWidget(self.commentUserLabel)
        self.commentTextLabel = QtWidgets.QPlainTextEdit(CommentWidget)
        self.commentTextLabel.setReadOnly(True)
        self.commentTextLabel.setObjectName("commentTextLabel")
        self.verticalLayout.addWidget(self.commentTextLabel)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(CommentWidget)
        QtCore.QMetaObject.connectSlotsByName(CommentWidget)

    def retranslateUi(self, CommentWidget):
        _translate = QtCore.QCoreApplication.translate
        CommentWidget.setWindowTitle(_translate("CommentWidget", "Form"))
        self.commentUserLabel.setText(_translate("CommentWidget", "评论者名称"))
