# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getMusicSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_getMusicSearch(object):
    def setupUi(self, getMusicSearch):
        getMusicSearch.setObjectName("getMusicSearch")
        getMusicSearch.resize(708, 534)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(getMusicSearch)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(getMusicSearch)
        self.label_2.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.getMusicSearchLayout = QtWidgets.QHBoxLayout()
        self.getMusicSearchLayout.setObjectName("getMusicSearchLayout")
        self.verticalLayout_2.addLayout(self.getMusicSearchLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(getMusicSearch)
        QtCore.QMetaObject.connectSlotsByName(getMusicSearch)

    def retranslateUi(self, getMusicSearch):
        _translate = QtCore.QCoreApplication.translate
        getMusicSearch.setWindowTitle(_translate("getMusicSearch", "Form"))
        self.label_2.setText(_translate("getMusicSearch", "搜索结果（音乐）"))
