# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'music_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(801, 80)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_time_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.left_time_label.setObjectName("left_time_label")
        self.horizontalLayout.addWidget(self.left_time_label)
        self.time_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.time_slider.setObjectName("time_slider")
        self.horizontalLayout.addWidget(self.time_slider)
        self.right_time_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.right_time_label.setObjectName("right_time_label")
        self.horizontalLayout.addWidget(self.right_time_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.play_mode_combo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.play_mode_combo.setObjectName("play_mode_combo")
        self.horizontalLayout_2.addWidget(self.play_mode_combo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.previous_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.previous_button.setObjectName("previous_button")
        self.horizontalLayout_2.addWidget(self.previous_button)
        self.suspend_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.suspend_button.setObjectName("suspend_button")
        self.horizontalLayout_2.addWidget(self.suspend_button)
        self.nex_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nex_button.setObjectName("nex_button")
        self.horizontalLayout_2.addWidget(self.nex_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.playlist_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.playlist_button.setObjectName("playlist_button")
        self.horizontalLayout_2.addWidget(self.playlist_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.left_time_label.setText(_translate("Form", "TextLabel"))
        self.right_time_label.setText(_translate("Form", "TextLabel"))
        self.previous_button.setText(_translate("Form", "上一首"))
        self.suspend_button.setText(_translate("Form", "暂停"))
        self.nex_button.setText(_translate("Form", "下一首"))
        self.playlist_button.setText(_translate("Form", "播放列表"))
