# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherShow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OtherShow(object):
    def setupUi(self, OtherShow):
        OtherShow.setObjectName("OtherShow")
        OtherShow.resize(908, 676)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(OtherShow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OtherShowUNameLabel = QtWidgets.QLabel(OtherShow)
        self.OtherShowUNameLabel.setStyleSheet("font: 26pt \"微软雅黑\";")
        self.OtherShowUNameLabel.setObjectName("OtherShowUNameLabel")
        self.horizontalLayout.addWidget(self.OtherShowUNameLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.OtherShowUIsVIPLabel = QtWidgets.QLabel(OtherShow)
        self.OtherShowUIsVIPLabel.setStyleSheet("border-bottom-color: rgb(85, 170, 0);")
        self.OtherShowUIsVIPLabel.setObjectName("OtherShowUIsVIPLabel")
        self.verticalLayout.addWidget(self.OtherShowUIsVIPLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(OtherShow)
        self.label_3.setStyleSheet("border-top-color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.OtherShowUSexLabel = QtWidgets.QLabel(OtherShow)
        self.OtherShowUSexLabel.setObjectName("OtherShowUSexLabel")
        self.horizontalLayout_2.addWidget(self.OtherShowUSexLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(OtherShow)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.OtherShowUIntroLabel = QtWidgets.QPlainTextEdit(OtherShow)
        self.OtherShowUIntroLabel.setReadOnly(True)
        self.OtherShowUIntroLabel.setObjectName("OtherShowUIntroLabel")
        self.horizontalLayout_3.addWidget(self.OtherShowUIntroLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(OtherShow)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.OtherShowUBirthdayLabel = QtWidgets.QLabel(OtherShow)
        self.OtherShowUBirthdayLabel.setObjectName("OtherShowUBirthdayLabel")
        self.horizontalLayout_4.addWidget(self.OtherShowUBirthdayLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(OtherShow)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.OtherShowULabelLabel = QtWidgets.QLabel(OtherShow)
        self.OtherShowULabelLabel.setObjectName("OtherShowULabelLabel")
        self.horizontalLayout_5.addWidget(self.OtherShowULabelLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.OtherShowDownLayout = QtWidgets.QHBoxLayout()
        self.OtherShowDownLayout.setObjectName("OtherShowDownLayout")
        self.verticalLayout.addLayout(self.OtherShowDownLayout)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 3)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 8)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(OtherShow)
        QtCore.QMetaObject.connectSlotsByName(OtherShow)

    def retranslateUi(self, OtherShow):
        _translate = QtCore.QCoreApplication.translate
        OtherShow.setWindowTitle(_translate("OtherShow", "Form"))
        self.OtherShowUNameLabel.setText(_translate("OtherShow", "好好好好好"))
        self.OtherShowUIsVIPLabel.setText(_translate("OtherShow", "并不是尊贵的会员"))
        self.label_3.setText(_translate("OtherShow", "性别"))
        self.OtherShowUSexLabel.setText(_translate("OtherShow", "TextLabel"))
        self.label_5.setText(_translate("OtherShow", "个人介绍"))
        self.label_7.setText(_translate("OtherShow", "生日"))
        self.OtherShowUBirthdayLabel.setText(_translate("OtherShow", "TextLabel"))
        self.label_9.setText(_translate("OtherShow", "喜欢的歌曲风格"))
        self.OtherShowULabelLabel.setText(_translate("OtherShow", "TextLabel"))
