# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FindMusic.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(561, 426)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, 10, 20, 10)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.FindMusicgraphicsView6 = QtWidgets.QGraphicsView(Form)
        self.FindMusicgraphicsView6.setObjectName("FindMusicgraphicsView6")
        self.gridLayout.addWidget(self.FindMusicgraphicsView6, 2, 2, 1, 1)
        self.FindMusicBtn3 = QtWidgets.QPushButton(Form)
        self.FindMusicBtn3.setObjectName("FindMusicBtn3")
        self.gridLayout.addWidget(self.FindMusicBtn3, 1, 2, 1, 1)
        self.FindMusicgraphicsView4 = QtWidgets.QGraphicsView(Form)
        self.FindMusicgraphicsView4.setObjectName("FindMusicgraphicsView4")
        self.gridLayout.addWidget(self.FindMusicgraphicsView4, 2, 0, 1, 1)
        self.FindMusicgraphicsView3 = QtWidgets.QGraphicsView(Form)
        self.FindMusicgraphicsView3.setObjectName("FindMusicgraphicsView3")
        self.gridLayout.addWidget(self.FindMusicgraphicsView3, 0, 2, 1, 1)
        self.FindMusicBtn1 = QtWidgets.QPushButton(Form)
        self.FindMusicBtn1.setObjectName("FindMusicBtn1")
        self.gridLayout.addWidget(self.FindMusicBtn1, 1, 0, 1, 1)
        self.FindMusicgraphicsView1 = QtWidgets.QGraphicsView(Form)
        self.FindMusicgraphicsView1.setObjectName("FindMusicgraphicsView1")
        self.gridLayout.addWidget(self.FindMusicgraphicsView1, 0, 0, 1, 1)
        self.FindMusicgraphicsView5 = QtWidgets.QGraphicsView(Form)
        self.FindMusicgraphicsView5.setObjectName("FindMusicgraphicsView5")
        self.gridLayout.addWidget(self.FindMusicgraphicsView5, 2, 1, 1, 1)
        self.FindMusicgraphicsView2 = QtWidgets.QGraphicsView(Form)
        self.FindMusicgraphicsView2.setObjectName("FindMusicgraphicsView2")
        self.gridLayout.addWidget(self.FindMusicgraphicsView2, 0, 1, 1, 1)
        self.FindMusicBtn2 = QtWidgets.QPushButton(Form)
        self.FindMusicBtn2.setObjectName("FindMusicBtn2")
        self.gridLayout.addWidget(self.FindMusicBtn2, 1, 1, 1, 1)
        self.FindMusicBtn4 = QtWidgets.QPushButton(Form)
        self.FindMusicBtn4.setObjectName("FindMusicBtn4")
        self.gridLayout.addWidget(self.FindMusicBtn4, 3, 0, 1, 1)
        self.FindMusicBtn5 = QtWidgets.QPushButton(Form)
        self.FindMusicBtn5.setObjectName("FindMusicBtn5")
        self.gridLayout.addWidget(self.FindMusicBtn5, 3, 1, 1, 1)
        self.FindMusicBtn6 = QtWidgets.QPushButton(Form)
        self.FindMusicBtn6.setObjectName("FindMusicBtn6")
        self.gridLayout.addWidget(self.FindMusicBtn6, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "发现音乐"))
        self.FindMusicBtn3.setText(_translate("Form", "PushButton"))
        self.FindMusicBtn1.setText(_translate("Form", "PushButton"))
        self.FindMusicBtn2.setText(_translate("Form", "PushButton"))
        self.FindMusicBtn4.setText(_translate("Form", "PushButton"))
        self.FindMusicBtn5.setText(_translate("Form", "PushButton"))
        self.FindMusicBtn6.setText(_translate("Form", "PushButton"))

